baseURL = 'https://suchstance.github.io/'
languageCode = 'en-us'
title = 'just a smattering of everything'
theme = 'PaperMod'

[markup.goldmark.renderer]
  unsafe = true

[params]
description = "just a smattering of everything"